name: Haxe-Formatter-Docs

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '15 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Formatter-Doc sources
      uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Run npm install
      run: npm ci
    - name: Run lix download
      run: npx lix download
    - name: Prepare
      run: |
        mkdir -p docs/samples/lineends
        mkdir -p site/css
        mkdir -p site/js
    - name: Build Site
      run: npx haxe build.hxml
    - name: Build JQueryUI
      run: |
        cd node_modules/jquery-ui
        npm i
        npx grunt concat requirejs uglify
    - name: Copy JQuery
      run: |
        cp node_modules/jquery/dist/jquery.min.js site/js/
        cp node_modules/jquery-ui/dist/jquery-ui.min.js site/js/
        cp node_modules/jquery-ui/dist/jquery-ui.css site/css/
        cp -vau node_modules/jquery-ui/themes/base/images site/css/
    - name: Run Sass
      run: npx sass css/formatter-docs.scss site/css/formatter-docs.css
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
